antvis/F2

- CONTRIBUTING.md
- CONTRIBUTING.zh-CN.md
> chore(contribute): add contribute.md

- src/chart/assist/scale.js
- test/unit/geom/geom-spec.js
* 修复绘制折线时第一条数据的值为 null 时的错误， close(#22 )
> fix(scale): fixed bug of first record with null

- src/chart/chart.js
- test/unit/chart/chart-spec.js
> feat: support CanvasRenderingContext2D instance.

- package.json
- src/chart/chart.js
- test/unit/chart/chart-spec.js
> fix: should use canvas dom's width.

- demos/line-hybrid.html
chore(demo): provide demo for hybrid-line-chart.
提供了一个实线/虚线混合的折线图的demo
> chore(demo) : provide demo for hybrid-line-chart

- CHANGELOG.md
- core.js
- demos/bar-animate.html
- package.json
- src/guide/text.js
- src/theme.js
> Publish 3.0.1

- src/geom/base.js
```js
chart.area({
startOnZero: false
}).position('time*tem')
.color('city')
//.shape('smooth')
.style({
opacity: 0.6
});
```
> feat: add startOnZero property for geom.

- src/graphic/g.js
- src/guide/index.js
- src/guide/tag.js
- src/theme.js
> feat: add guide-tag

- CHANGELOG.md
- README.md
- package.json
> publish 3.0.2

- src/chart/assist/axis.js
- test/unit/chart/assist/axis-spec.js
> feat: support setting axis's position.

- demos/area.html
- demos/bottom-legend.html
- demos/column-group.html
- demos/index.njk
- demos/left-legend.html
- demos/right-legend.html
- demos/smooth-line.html
- package.json
- src/chart/chart.js
- src/chart/controller/axis.js
- src/component/axis/abstract.js
- src/coord/base.js
- src/coord/cartesian.js
- src/coord/polar.js
- src/plugin/guide.js
- src/plugin/legend.js
- src/theme.js
- src/util/common.js
- test/unit/axis/circle-axis-spec.js
- test/unit/axis/line-axis-spec.js
- test/unit/chart/controller/axis-spec.js
> feat: auto padding.

- CHANGELOG.md
- package.json
> publish v3.0.3

- demos/area-00.html
- src/chart/chart.js
- test/unit/chart/chart-spec.js
> feat: add chart.scale()

- package.json
- src/geom/base.js
- src/geom/shape/interval.js
- src/plugin/tooltip.js
- test/bug/issue-67-spec.js
- test/unit/geom/geom-spec.js
> Get snap records

- demos/multiple-y-guide.html
- package.json
- src/component/guide/base.js
- src/plugin/guide.js
- test/unit/guide/arc-spec.js
- test/unit/guide/base-spec.js
- test/unit/guide/html-spec.js
- test/unit/guide/line-spec.js
- test/unit/guide/rect-spec.js
- test/unit/guide/text-spec.js
- test/unit/plugin/guide-spec.js
> feat: support multiple y axis for guide. Closed #64

- demos/area-00.html
- docs/api/guide.md
- docs/getting-started/require-on-demand.md
- package.json
- src/component/guide/index.js
- src/component/guide/tag.js
- src/component/guide/text.js
- src/plugin/guide.js
- test/unit/guide/tag-spec.js
- test/unit/plugin/guide-spec.js
迁移 chart.guide().tag()，api 使用如下：
```js
chart.guide().tag({
top: {Boolean}, // 指定 guide 是否绘制在 canvas 最上层，默认为 true, 即绘制在最上层
position: {Function} | {Array}, // Tag 的起始位置，值为原始数据值，支持 callback
content: {String}, // tag 的文本内容
direct: 'tl', // 默认的箭头朝向
side: 4, //  三角标的边长
offsetX: 0, // X 轴偏移
offsetY: 0, // Y 轴偏移
backgroud: {
padding: [ 4, 6 ], // tag 内边距
radius: 2, // tag 圆角
fill: '#1890FF', // tag 背景色
}, // 背景样式
textStyle: {
fontSize: 12,
fill: '#fff'
} // 文本样式
});
```
> Feat guide tag

- demos/changesize.html
- demos/index.njk
- demos/performance.html
- demos/time-line-update.html
- docs/api/chart.md
- docs/api/global.md
- docs/api/guide.md
- package.json
- src/animation/detail.js
- src/animation/group.js
- src/chart/chart.js
- src/global.js
- src/graphic/animate/animator.js
- src/graphic/animate/timeline.js
- src/graphic/canvas.js
- src/scale/linear.js
- test/unit/chart/chart-spec.js
- test/unit/graphic/animate-spec.js
> Animate performance

- demos/multiple.html
- demos/ring.html
- package.json
- src/geom/base.js
- test/bug/issue-57-spec.js
> fix: set min and max for interval is not work. Closed #57

- package.json
- src/geom/area.js
- src/geom/shape/util.js
- src/plugin/tooltip.js
> fix: support area with null data

- src/chart/controller/axis.js
- test/unit/chart/chart-spec.js
> fix: axis label fontFamily

- README.md
- docs/getting-started/require-on-demand.md
- package.json
- src/chart/controller/axis.js
- src/graphic/animate/animator.js
- src/graphic/animate/timeline.js
- src/graphic/canvas.js
- src/graphic/shape/text.js
- src/plugin/tooltip.js
- src/util/dom.js
> animate strengthen && node support

- docs/api/gesture.md
- package.json
- src/plugin/gesture.js
- src/util/common.js
- test/bug/issue-67-spec.js
- test/bug/issue-83-spec.js
- test/unit/plugin/gesture-spec.js
- test/unit/plugin/legend-spec.js
- test/unit/plugin/tooltip-spec.js
- test/unit/test-util.js
> feat: add gesture plugin

- src/geom/base.js
- test/bug/issue-67-spec.js
> fix: getSnapRecords() - pick data more accurate in pie chart.

- src/chart/chart.js
- test/unit/chart/chart-spec.js
> fix: prevent same plugins repeat init.

- .travis.yml
- CHANGELOG.md
- README.md
- README.zh-CN.md
> Publish 318

- src/chart/chart.js
- src/geom/base.js
- test/bug/issue-136-spec.js
> fix: fix the interval y scale unable to set min.

- src/chart/controller/scale.js
- test/bug/issue-140-spec.js
> fix: fix the error when values are all null in linear scale.

- demos/area-02.html
- demos/pie-00.html
- src/chart/chart.js
- src/chart/controller/scale.js
- src/component/list.js
- src/geom/base.js
- src/graphic/shape/text.js
- src/plugin/legend.js
- src/scale/time-cat.js
- test/bug/issue-145-spec.js
- test/bug/issue-151-spec.js
> feat: add unCheckStyle for legend.

- demos/0-interacion-interval-select.html
- demos/0-interacion-pie-select.html
- src/interaction/interval-select.js
- src/interaction/pie-select.js
> feat: pie-select and interval-select support cancelable property.

- src/geom/area.js
- src/geom/base.js
- src/geom/path.js
- src/geom/shape/util.js
- test/bug/issue-119-spec.js
- test/bug/issue-136-spec.js
- test/bug/issue-140-spec.js
- test/bug/issue-145-spec.js
- test/bug/issue-151-spec.js
- test/bug/issue-171-spec.js
> feat: add connectNulls for geometry to connect null points. Closed #171.

- src/geom/adjust/stack.js
- test/bug/issue-173-spec.js
> fix: filter null values when draw stacked point chart. Closed #173.

- CHANGELOG.md
- package.json
- src/chart/chart.js
- src/geom/base.js
- src/geom/shape/area.js
- src/global.js
- src/plugin/tooltip.js
- test/bug/issue-179-spec.js
- test/bug/issue-180-spec.js
> F2 3.1.14 

- README.md
> docs: Fix some typo in readme

- LICENSE
- demos/0-interacion-pan-x.html
- src/component/guide/arc.js
- src/component/guide/base.js
- src/component/guide/html.js
- src/component/guide/line.js
- src/component/guide/rect.js
- src/component/guide/region-filter.js
- src/component/guide/tag.js
- src/component/guide/text.js
- src/geom/base.js
- src/interaction/pan.js
- src/interaction/pinch.js
- test/bug/issue-203-spec.js
- test/unit/guide/base-spec.js
> 07-23 BUG fix

- src/chart/controller/axis.js
- src/plugin/legend.js
> feat: appendPadding support Array, just like padding. Closed #195。

- src/component/list.js
- src/component/tooltip.js
- test/bug/issue-216-spec.js
> fix: Fix problem with element zIndex in tooltip. Closed #216

- demos/0-interacion-interval-select.html
- package.json
- src/global.js
- src/interaction/interval-select.js
- src/interaction/pan.js
> Fix issue 221

- demos/0-interacion-pie-select.html
- package.json
- src/global.js
- src/interaction/pie-select.js
> fix: when chart's data changed, clear the append shape. Closed #227.

- package.json
- src/component/guide/html.js
- src/global.js
- test/unit/guide/html-spec.js
> chore: handle the compatibility of Element.prototype.remove().

- src/geom/base.js
- test/bug/issue-234-spec.js
- test/bug/issue-235-spec.js
- test/bug/issue-238-spec.js
> fix: fix the error caused by empty data.Closed #238.

- CHANGELOG.md
- demos/line-01.html
- package.json
- src/chart/controller/scale.js
- src/global.js
- src/plugin/scroll-bar.js
> Daily 0814

- package.json
- src/component/guide/base.js
- src/global.js
- src/plugin/guide.js
- test/unit/plugin/guide-spec.js
> Feat guide repaint

- demos/multiple-y-guide.html
- src/chart/chart.js
- src/geom/base.js
- test/bug/issue-257-spec.js
- test/unit/chart/chart-spec.js
> Feat sync y

- src/geom/shape/area.js
- src/graphic/element.js
- src/graphic/util/style-parse.js
- test/unit/graphic/element-spec.js
> feat: support set gradient color in default. Closed #243.

- package.json
- src/global.js
- src/util/common.js
> compatible vue.js. Related#263.

- src/animation/detail.js
- [x ] `npm test` passes
- [ x] tests and/or benchmarks are included
- [x ] commit message follows commit guidelines
fix  guide-tag animate error
> fix: guide-tag animate error

- src/geom/base.js
- src/plugin/tooltip.js
- test/bug/issue-273-spec.js
- test/unit/plugin/tooltip-spec.js
> Fix tooltip bugs

- .travis.yml
This ads Node.js 10 to the Travis CI pipeline to test the current stable branch of Node.js.
> tests: add Node.js 10

- src/component/guide/base.js
- test/unit/guide/base-spec.js
> feat: position support for mixing of keyword, percent and value.

- .babelrc
- package.json
> chore: upgrade babel7.

- src/component/guide/base.js
- test/unit/guide/base-spec.js
> Revert "feat: position support for mixing of keyword, percent and value."

- CHANGELOG.md
- package.json
- src/global.js
> 3.2.2-beta.1 release

- src/animation/detail.js
- test/bug/issue-318-spec.js
> fix: Optimized geometry shape's id generation strategy. Closed #318.

- src/graphic/shape/polyline.js
> fix: when the points is empty, return. Closed #316.

- CHANGELOG.md
- package.json
- src/global.js
> release 3.2.3

- src/geom/shape/area.js
> fix: fix the draw error caused by smooth area animation. Closed #373.

- demos/candlestick.html
- src/component/text-box.js
- src/component/tooltip.js
- src/plugin/tooltip.js
- test/unit/plugin/tooltip-spec.js
…support xTip and yTip display for tooltip. Closed #369.
> WIP: Tooltip enhancement

- demos/pie-with-iconfont-and-label.html
- src/index-all.js
- src/plugin/pie-label.js
- test/unit/plugin/pie-label-spec.js
> Feat pie label

- src/graphic/util/style-parse.js
> fix: fix angle calculation problem with linear gradient.

- src/graphic/util/style-parse.js
> Revert "fix: fix angle calculation problem with linear gradient."

- demos/tiny-cat-pan.html
- demos/tiny-cat-pinch.html
- demos/tiny-timecat-pan.html
- demos/tiny-timecat-pinch.html
- package.json
- src/global.js
- src/interaction/pan.js
- src/interaction/pinch.js
- test/unit/interaction/pinch-spec.js
> Pan pinch strengthen

- demos/0-interacion-pinch-pan-timecat.html
- src/chart/chart.js
- src/interaction/helper.js
- src/interaction/mixin/move.js
- src/interaction/mixin/press-tooltip.js
- src/interaction/pan.js
- src/interaction/pinch.js
- src/plugin/filter.js
- src/plugin/scroll-bar.js
- src/plugin/tooltip.js
> Strength swipe

- demos/0-interacion-pinch-pan-timecat.html
- src/component/tooltip.js
- src/interaction/helper.js
- src/interaction/mixin/move.js
- src/interaction/mixin/update-scale.js
- src/interaction/pan.js
- src/interaction/pinch.js
- src/plugin/scroll-bar.js
- src/util/common.js
- test/unit/component/axis/circle-axis-spec.js
- test/unit/component/axis/line-axis-spec.js
- test/unit/component/guide/arc-spec.js
- test/unit/component/guide/base-spec.js
- test/unit/component/guide/html-spec.js
- test/unit/component/guide/line-spec.js
- test/unit/component/guide/point-spec.js
- test/unit/component/guide/rect-spec.js
- test/unit/component/guide/tag-spec.js
- test/unit/component/guide/text-spec.js
- test/unit/component/index-spec.js
- test/unit/graphic/easing-spec.js
- test/unit/interaction/pan-spec.js
- test/unit/interaction/pinch-spec.js
- test/unit/interaction/swipe-spec.js
- test/unit/plugin/tooltip-spec.js
- test/unit/util/common-spec.js
> add test cases.

- src/component/guide/base.js
- test/unit/component/guide/base-spec.js
- test/unit/component/guide/html-spec.js
- test/unit/component/guide/line-spec.js
> feat: Guide component support change visible.

- src/plugin/tooltip.js
- test/unit/plugin/tooltip-spec.js
> feat: support snap property for crosshairs.

- src/chart/controller/axis.js
> fix: filter grid points which not in the range 0 to 1.

- src/graphic/shape/arc.js
- test/unit/graphic/shape/arc-spec.js
> fix: Arc shape support fill. Closed #429.

- demos/multiple.html
- src/chart/chart.js
> fix(syncYScales): scale should re-calculate the ticks

- CHANGELOG.md
- package.json
- src/component/tooltip.js
- src/global.js
> Feat miniprogram support

- CHANGELOG.md
- package.json
- src/global.js
> release 3.3.5

- package.json
- src/global.js
- src/graphic/shape/sector.js
- src/interaction/helper.js
- test/bug/issue-514-spec.js
> Daily 0218

- package.json
- src/chart/controller/scale.js
- src/global.js
> update @antv/scale & @antv/attr

- package.json
- src/global.js
- src/graphic/shape/sector.js
- test/bug/issue-514-spec.js
> 资产白屏的 BUG 修复

- package.json
- src/global.js
- src/graphic/shape/sector.js
> 当只有1个扇形时，角度计算-6.285040585751744e-7和0，相减小于0.0001，也不绘制

- src/graphic/shape/arc.js
> 圆弧开始结束相同时不绘制，chrome的lineCap为round时会有个圆点

- src/interaction/pie-select.js
- test/unit/interaction/pie-select-spec.js
> fix guide.repaint will remove halo

- .travis.yml
- package.json
- src/global.js
- src/index.js
> feat: 默认增加guide point插件

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/----please-use-antv-issue-helper---.md
- Use new issue template from https://antv-issue-helper.surge.sh
> chore: Use new issue template

- src/component/guide/base.js
- test/unit/component/guide/base-spec.js
> fix: Guide 的 position 百分比解析需要考虑原始数据中本身包含 '%'

- src/plugin/legend.js
- test/bug/legend-filter-spec.js
> fix: 修复图例过滤不考虑空数据的问题。

- examples/basic/demo/basic.js
- gatsby-config.js
- package.json
https://github.com/antvis/gatsby-theme-antv/commit/aa8cdd7e24e965174cbe7173a841fd7d23537e52
> fix: f2 example throw require is not defined

- src/geom/base.js
- test/bug/issue-67-spec.js
> fix: 修复对类型换图点击选中的问题 #682

- src/geom/base.js
- test/bug/issue-702-spec.js
> fix: 修复只有1个点时，tooltip不显示的问题 #702

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.4.3

- docs/api/chart/coordinate.en.md
- docs/api/chart/coordinate.zh.md
- docs/api/chart/interaction.en.md
- docs/api/chart/interaction.zh.md
- docs/api/chart/pie-label.en.md
- docs/api/chart/pie-label.zh.md
- docs/api/chart/scale.en.md
- docs/api/chart/scale.zh.md
- docs/api/chart/tooltip.en.md
- docs/api/chart/tooltip.zh.md
- docs/api/graphic/g.en.md
- docs/api/graphic/g.zh.md
- docs/api/graphic/group.en.md
- docs/api/graphic/group.zh.md
- docs/api/graphic/shape.en.md
- docs/api/graphic/shape.zh.md
- docs/api/shape.en.md
- docs/api/shape.zh.md
- docs/tutorial/getting-started.en.md
- docs/tutorial/getting-started.zh.md
- docs/tutorial/manual/scale.en.md
- docs/tutorial/manual/scale.zh.md
- docs/tutorial/question.en.md
- docs/tutorial/question.zh.md
- site/pages/index.zh.tsx
> Feat new site

- src/interaction/mixin/move.js
- test/unit/interaction/pan-spec.js
> fix: 滑动x轴时，cat的ticks会被置成null

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.4.4

- docs/api/chart/chart.en.md
- docs/api/chart/chart.zh.md
> docs: 添加filter的使用说明

- demos/interval-symmetric.html
- src/coord/base.js
- src/coord/cartesian.js
- src/coord/polar.js
- src/geom/adjust/index.js
- src/geom/adjust/symmetric.js
- src/geom/base.js
- src/geom/shape/interval.js
- src/index-all.js
- src/plugin/interval-label.js
- test/unit/coord/base-spec.js
- test/unit/geom/geom-spec.js
- test/unit/plugin/interval-label-spec.js
> feat: 添加漏斗图

- package.json
- src/global.js
> release 3.5-beta.2

- examples/funnel/basic/demo/basic.js
- examples/funnel/basic/demo/meta.json
- examples/funnel/basic/demo/stroke.js
- examples/funnel/basic/index.en.md
- examples/funnel/basic/index.zh.md
- examples/funnel/pyramid/demo/basic.js
- examples/funnel/pyramid/demo/meta.json
- examples/funnel/pyramid/demo/scale.js
- examples/funnel/pyramid/demo/stroke.js
- examples/funnel/pyramid/index.en.md
- examples/funnel/pyramid/index.zh.md
- gatsby-config.js
> feat: 添加漏斗图演示demo

- package.json
- src/global.js
- src/graphic/canvas-element.js
> refactor: 去掉eventemitter，只要简单的事件处理就可以了

- package.json
- src/global.js
- src/graphic/canvas-element.js
> fix: 修复非浏览器环境时，currentStyle报错

- .npmignore
- package.json
- src/global.js
> chore: npm包添加src源文件

- src/plugin/tooltip.js
> fix: 未设置geometry时，clear报错

- package.json
- src/global.js
> chore: 发布3.5.0-beta.6

- src/plugin/tooltip.js
> fix: 修复tooltip touchend不消失的问题

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.5.0

- .eslintrc
- package.json
- src/util/array.js
- src/util/common.js
- src/util/dom.js
- src/util/helper.js
- test/bug/issue-467-spec.js
- test/bug/issue-468-spec.js
- test/bug/issue-488-spec.js
- test/bug/issue-514-spec.js
- test/bug/issue-543-spec.js
- test/bug/issue-550-spec.js
- test/bug/issue-586-spec.js
- test/bug/legend-filter-spec.js
- test/unit/attr/base-spec.js
- test/unit/chart/controller/scale-spec.js
- test/unit/component/axis/line-axis-spec.js
- test/unit/component/guide/arc-spec.js
- test/unit/coord/circle-spec.js
- test/unit/graphic/shape/text-spec.js
- test/unit/plugin/gesture-spec.js
> feat: 升级@antv/util

- src/graphic/canvas.js
- src/graphic/event/controller.js
- src/graphic/event/emit.js
- src/util/dom.js
> feat: 添加内部的事情处理

- package.json
- src/attr/base.js
- src/attr/color-util.js
- src/attr/color.js
- src/attr/index.js
- src/attr/opacity.js
- src/attr/position.js
- src/attr/shape.js
- src/attr/size.js
- src/chart/chart.js
- src/chart/const.js
- src/chart/controller/scale.js
- src/geom/base.js
- src/geom/interval.js
- src/geom/mixin/size.js
- src/geom/point.js
- src/geom/schema.js
- src/graphic/event/controller.js
- src/graphic/event/emit.js
- src/interaction/helper.js
- src/interaction/mixin/move.js
- src/interaction/mixin/update-scale.js
- src/interaction/pinch.js
- test/bug/issue-140-spec.js
- test/bug/issue-273-spec.js
- test/unit/attr/color-spec.js
- test/unit/chart/chart-spec.js
- test/unit/geom/geom-spec.js
> Refactor geom cache

- src/chart/chart.js
- src/chart/const.js
- src/index.js
- src/interaction/base.js
- src/interaction/new/base.js
- src/interaction/new/context.js
- src/interaction/new/index.js
- src/interaction/new/pan.js
- src/interaction/new/pinch.js
- src/interaction/pan.js
- src/interaction/pinch.js
- src/interaction/register.js
- src/plugin/legend.js
- src/plugin/pie-label.js
- src/plugin/tooltip.js
- src/util/common.js
- test/unit/interaction/new/compatible-spec.js
- test/unit/interaction/new/data.json
- test/unit/interaction/new/index-spec.js
> feat: 复杂交互支持小程序

- .github/workflows/ci.yml
- package.json
- test/bug/issue-514-spec.js
> feat: Create ci.yml

- src/chart/chart.js
- src/interaction/new/base.js
- src/interaction/new/context.js
- src/interaction/new/pinch.js
> feat: pinch 添加range配置

- package.json
- src/global.js
> chore: release 3.6.0

- src/graphic/canvas.js
- test/unit/graphic/canvas-spec.js
> fix: ios spa多次创建导致canvas白屏。Closed #630

- package.json
> fix: 添加browser字段。Closed #789

- package.json
- src/global.js
> chore: release 3.6.1

- docs/api/f2.en.md
- docs/api/f2.zh.md
> fix: 修复官网的链接问题

- src/core.js
- src/index.js
- test/unit/core-spec.js
> feat: 把helper和component透出来

- src/geom/base.js
- test/bug/issue-797-spec.js
> fix: render 之后再次修改geom的size. Closed #797

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.6.2

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.6.3

- .github/workflows/gitleaks.yml
> chore: add leaks action

- .github/workflows/ci.yml
- src/interaction/new/base.js
- test/unit/interaction/new/index-spec.js
- test/unit/test-util.js
> Fix interaction event hooks

- package.json
- src/global.js
> chore: release 3.6.4-beta.1

- src/geom/base.js
- src/interaction/new/context.js
- test/unit/geom/geom-spec.js
> feat: geom添加getRecords方法

- package.json
- src/global.js
> chore: release 3.6.4-beta.2

- package.json
- src/global.js
> chore: release 3.6.4-beta.3

- src/chart/chart.js
- src/chart/const.js
- src/chart/controller/scale.js
> feat: 添加geom draw 事件

- package.json
- src/global.js
> chore: release 3.6.4-beta.4

- package.json
- src/global.js
> chore: release 3.7.0-alpha.0

- .babelrc
- package.json
- src/coord/cartesian.js
- src/geom/area.js
- src/geom/shape/index.js
- src/geom/shape/line.js
- src/interaction/helper.js
> fix: 修复site编译报错的问题

- package.json
- src/global.js
> chore: release 3.7.0-alpha.1

- src/graphic/shape/rect.js
- test/unit/graphic/shape/rect-spec.js
> fix: 修复rect radius大于宽高时，图形绘制不正确

- package.json
- src/global.js
> chore: release 3.6.4-beta.5

- package.json
- src/interaction/mixin/move.js
- src/interaction/mixin/update-scale.js
- src/interaction/pan.js
- src/interaction/pinch.js
- src/interaction/swipe.js
> fix: module mix fixed

- src/interaction/new/base.js
- src/interaction/new/context.js
> fix: 交互销毁时，注销事件

- package.json
- src/global.js
> chore: release 3.6.4-beta.6

- package.json
- src/global.js
> chore: release 3.7.0-alpha.2

- src/graphic/event/controller.js
> fix: 修复touchstart触发press时，没有设置direction

- package.json
- src/global.js
> chore: release 3.6.4-beta.7

- test/unit/graphic/event/controller-spec.js
> test: 补充event controller的单测

- package.json
- src/global.js
> chore: release 3.6.4-beta.8

- examples/component/guide/index.zh.md
- examples/other/other/demo/meta.json
- examples/other/other/index.zh.md
- examples/relation/relation/demo/meta.json
- examples/relation/relation/index.en.md
- examples/relation/relation/index.zh.md
- gatsby-config.js
- package.json
- src/index-all.js
> fix: site 官网的一些错误

- examples/relation/relation/demo/meta.json
- examples/relation/relation/index.zh.md
- package.json
> fix: site build error

- src/chart/chart.js
- src/geom/base.js
- test/unit/geom/geom-init-spec.js
> feat: adjust interval

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.6.4

- src/graphic/index.js
- src/graphic/shape/image.js
- test/unit/graphic/shape/image-spec.js
> feat: add image shape

- docs/api/graphic/shape.en.md
- docs/api/graphic/shape.zh.md
- examples/component/image/demo/image.js
- examples/component/image/demo/meta.json
- examples/component/image/index.en.md
- examples/component/image/index.zh.md
- test/unit/graphic/shape/image-spec.js
> feat: 新增图片型图形文档和demo

- package.json
- src/global.js
> chore: release 3.7.0-alpha.5

- package.json
- src/global.js
> chore: release 3.7.0-alpha.6

- test/unit/graphic/canvas-spec.js
- types/Plot.d.ts
- types/Util.d.ts
- types/index.d.ts
> fix: 补充types的定义

- package.json
- src/global.js
> chore: release 3.7.0-alpha.7

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.7.0

- docs/api/chart/gesture.en.md
- docs/api/chart/gesture.zh.md
- docs/tutorial/manual/miniprogram.en.md
- docs/tutorial/manual/miniprogram.zh.md
- docs/tutorial/manual/node-env.en.md
- docs/tutorial/manual/node-env.zh.md
> docs: 修复文档上一些失效的链接

- gatsby-config.js
> docs: uniform AntV navbar's order and naming

- docs/tutorial/getting-started.en.md
- docs/tutorial/getting-started.zh.md
> docs: modify f2 cdn url

- package.json
- src/chart/controller/scale.js
- src/geom/base.js
- src/index-all.js
- src/index.js
- src/interaction/helper.js
- src/interaction/mixin/update-scale.js
- src/interaction/new/context.js
- src/plugin/filter.js
- src/scale/index.js
- src/scale/time-cat.js
- src/util/common.js
- test/bug/guide-html-spec.js
- test/bug/issue-151-spec.js
- test/bug/issue-216-spec.js
- test/bug/issue-550-spec.js
- test/unit/animation/detail-spec.js
- test/unit/chart/chart-spec.js
- test/unit/interaction/pan-spec.js
- test/unit/interaction/pinch-spec.js
- test/unit/plugin/guide-spec.js
> deps: 升级@antv/scale

- src/plugin/pie-label.js
- test/unit/plugin/pie-label-spec.js
> fix: 修复pieLabel插件判断矩形重叠的函数

- package.json
- src/global.js
> chore: release 3.7.1-beta.1

- .babelrc
- package.json
- test/bug/issue-804-spec.js
> fix: transform arrow functions

- package.json
- src/global.js
> chore: release 3.7.1-beta.2

- examples/area/stacked/demo/area-none.js
- examples/candlestick/basic/demo/basic.js
- examples/candlestick/basic/demo/daily.js
- examples/candlestick/basic/demo/hour.js
- examples/column/basic/demo/pan.js
- examples/component/axis/demo/grid.js
- examples/component/axis/demo/label-callback.js
- examples/component/guide/demo/line.js
- examples/component/guide/demo/point.js
- examples/component/legend/demo/align.js
- examples/gallery/fitness-ring/demo/apple-watch.js
- examples/gallery/forecast/demo/basic.js
- examples/gallery/gauge/demo/basic.js
- examples/gallery/steps-record/demo/basic.js
- examples/heatmap/heatmap/demo/polar.js
- examples/line/basic/demo/pan.js
- examples/line/multiple/demo/series.js
- examples/line/other/demo/null.js
- examples/other/other/demo/word-cloud.js
- examples/point/scatter/demo/scatter.js
- src/animation/animate.js
- 替换demo数据的相对路径为cdn（沙盒问题）；
- 增加部分demo注释
- 修复部分环境下（CodeSandBox可复现）注册Animation报错的问题 #957
> Fix demo data path

- src/chart/chart.js
- src/chart/const.js
- test/unit/interaction/new/index-spec.js
> feat: 添加repaint事件

- package.json
- src/global.js
> chore: release 3.7.2

- examples/funnel/basic/demo/basic.js
- examples/funnel/basic/demo/stroke.js
- examples/funnel/pyramid/demo/basic.js
- examples/funnel/pyramid/demo/scale.js
- examples/funnel/pyramid/demo/stroke.js
- src/geom/adjust/index.js
- src/plugin/interval-label.js
- test/unit/plugin/interval-label-spec.js
- test/unit/test-util.js
> fix: 修复漏斗图legend点击后，label位置不调整 Fixed #979

- src/interaction/pan.js
- test/bug/issue-954-spec.js
> fix: 修复 interval 平移后不显示的问题 Fixed #954

- src/scale/linear-tick.js
- test/unit/scale/linear-tick-spec.js
> chore: 调整代码结构

- src/geom/base.js
- test/bug/issue-954-spec.js
- test/unit/geom/geom-spec.js
- test/unit/interaction/new/index-spec.js
> fix: 修复数据字段存在x,y时，再次mapping后，数据不对

- src/scale/linear-tick.js
- test/unit/scale/linear-tick-spec.js
> fix: 特殊情况下interval不满足要求时，需要递归计算

- src/interaction/new/context.js
- src/scale/cat-tick.js
- src/scale/index.js
- test/unit/interaction/new/index-spec.js
- test/unit/scale/cat-spec.js
> fix: 统一cat ticks 计算

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.7.3

- docs/tutorial/manual/node-env.en.md
- docs/tutorial/manual/node-env.zh.md
- docs/tutorial/manual/require.en.md
- docs/tutorial/manual/require.zh.md
- src/scale/time-cat.js
> Time cat export

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.7.4

- src/scale/linear-tick.js
- test/bug/issue-145-spec.js
- test/unit/plugin/interval-label-spec.js
- test/unit/scale/linear-tick-spec.js
> fix: 修复当interval为小数时，小数位数会少1位

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.7.5

- src/scale/linear-tick.js
- test/unit/scale/linear-tick-spec.js
> fix: linear NaN error

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.7.6

- src/component/text-box.js
- src/component/tooltip.js
> fix: 修复tooltip showXTip 显示时，measureText需要新建canvas. Fixed #1015

- src/graphic/animate/animator.js
- src/graphic/animate/timeline.js
> fix: 修复动画空执行

- src/plugin/tooltip.js
- test/unit/plugin/tooltip-spec.js
- test/unit/test-util.js
> fix: 修复alwaysshow为true时，滑动到plot外面，tooltip还会隐藏的问题

- src/graphic/canvas.js
- src/graphic/container.js
- src/graphic/group.js
> chore: group和canvas的drawInner统一到container里

- src/chart/chart.js
- src/coord/base.js
- src/graphic/element.js
- src/graphic/util/matrix.js
- test/bug/issue-1004-spec.js
> fix: 双y轴， getPosition取不到point. Fixed #1004

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.7.7

- src/global.js
- src/interaction/base.js
> fix 主题设置问题和hammerjs引用导致小程序端报错问题

- package.json
- src/global.js
> chore: release 3.7.8

- src/index.js
> feat: export tooltip component

- src/aria-lang.CN.js
- src/chart/chart.js
- src/chart/controller/axis.js
- src/geom/aria/util.js
- src/geom/base.js
- src/global.js
- src/graphic/canvas-element.js
- src/graphic/canvas.js
- src/graphic/container.js
- src/graphic/element.js
- src/graphic/shape/text.js
- src/plugin/legend.js
- src/util/common.js
- test/fixtures/accessibility-spec.js
- test/unit/graphic/canvas-spec.js
- test/unit/plugin/legend-spec.js
> feat: 添加shape的无障碍处理

- docs/api/chart/chart.zh.md
- examples/basic/demo/meta.json
- examples/column/basic/demo/aria.js
- examples/column/basic/demo/meta.json
- examples/line/basic/demo/aria.js
- examples/line/basic/demo/meta.json
> docs: 添加无障碍aria的配置和使用文档

- package.json
- src/global.js
> chore: release 3.8.0-alpha.1

- types/Chart.d.ts
> chore: chart types 添加renderer参数

- docs/api/chart/tooltip.zh.md
> docs: 添加tooltip show hide 的文档说明

- examples/creative/case/demo/landscape.js
- gatsby-config.js
> docs: 修改demo

- package.json
- src/global.js
> chore: release 3.8.0-alpha.2

- .github/workflows/mirror.yml
- src/util/dom.js
> fix: remove circular dependency

- site/pages/index.zh.tsx
> docs: 修改官网首页example链接

- package.json
- src/global.js
> chore: release 3.8.0

- CHANGELOG.md
> docs: 修改changelog

- src/animation/detail.js
- test/bug/issue-1102-spec.js
> fix: 修复repaint shape属性不生效。Closed #1102

- src/graphic/animate/animator.js
- src/graphic/animate/timeline.js
- test/bug/issue-1102-spec.js
> fix: 修复repaint时动画不生效

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.8.1

- examples/creative/case/demo/landscape.js
> docs: fix landscape examples

- .travis.yml
- src/component/tooltip.js
- src/plugin/tooltip.js
- test/unit/plugin/tooltip-spec.js
> fix: 修复tooltip posy小于0被截断不显示

- src/graphic/engine/canvas.js
- src/graphic/engine/container.js
- src/graphic/engine/group.js
- test/unit/graphic/group-spec.js
> feat: group 支持添加背景

- src/graphic/engine/element.js
- test/bug/issue-1140-spec.js
> fix: 修复hollowCircle报错和多geom时，crosshairs不显示的问题。Fixed #1140

- src/graphic/engine/shape/image.js
- src/graphic/engine/shape/rect.js
- test/unit/graphic/shape/image-spec.js
> feat: image 添加 radius 属性

- src/graphic/event/controller.js
- src/util/dom.js
- test/unit/graphic/event/controller-spec.js
> fix: 修复touchend 后，points为空

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.8.2

- src/graphic/engine/shape/rect.js
- test/unit/graphic/shape/rect-spec.js
> fix: rect 设置radius时，图形画不出来

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.8.3

- src/interaction/mixin/move.js
- test/unit/interaction/pan-spec.js
> fix: cat类型平移后ticks不更新

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.8.4

- src/interaction/mixin/move.js
- test/unit/interaction/pan-spec.js
> fix: 连续平移后tick计算不对

- package.json
- src/global.js
> chore: release 3.8.6

- src/graphic/engine/element.js
- test/unit/graphic/group-spec.js
> fix: 修复group背景色绘制不正确

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.8.7

- src/graphic/engine/shape/image.js
- test/unit/graphic/shape/image-spec.js
> feat: image shape 支持fillOpacity设置

- src/graphic/engine/shape/image.js
> fix: 修复添加图片后，toDataURL 报 SecurityError

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.8.8

- src/graphic/engine/shape/image.js
- test/unit/graphic/shape/image-spec.js
> feat: 图片添加缓存配置，防止重复加载的抖动

- CHANGELOG.md
- package.json
- src/global.js
> chore: release 3.8.9

- src/interaction/mixin/move.js
- src/interaction/pan.js
> fix: 修复panstart时图表的跳动问题

- package.json
- src/global.js
> chore: beta 3.8.10

- package.json
- test/unit/graphic/shape/rect-spec.js
> fix: 修复site build 报错

- docs/api/chart/interaction.en.md
> docs: Update interaction.en.md

- .prettierrc.yml
- packages/site/examples/area/basic/demo/basic.js
- packages/site/examples/area/basic/demo/gradient.js
- packages/site/examples/area/basic/demo/with-negative-not-start-on-zero.js
- packages/site/examples/area/basic/demo/with-negative.js
- packages/site/examples/area/stacked/demo/area-none.js
- packages/site/examples/area/stacked/demo/percent.js
- packages/site/examples/area/stacked/demo/stacked.js
- packages/site/examples/data/race-country.json
- packages/site/examples/line/basic/demo/basic.js
- packages/site/examples/line/basic/demo/smooth.js
- packages/site/examples/line/basic/demo/with-point.js
- packages/site/examples/line/multiple/demo/customize-tootlip.js
- packages/site/examples/line/multiple/demo/series.js
- packages/site/examples/line/multiple/demo/shapes.js
- packages/site/package.json
- 迁移折线图和面积图 demo 到 4.0
- 补充了 .prettierrc
> 迁移折线图和面积图 demo

- package.json
> chore: 修复官网文档代码块不换行

- packages/site/examples/bar/basic/demo/basic.js
- packages/site/examples/bar/basic/demo/range.js
- packages/site/examples/bar/dodge/demo/dodge.js
- packages/site/examples/bar/dodge/demo/negetive.js
- packages/site/examples/bar/stack/demo/percent.js
- packages/site/examples/bar/stack/demo/stack.js
- packages/site/examples/point/scatter/demo/bubble.js
- packages/site/examples/point/scatter/demo/ordered-bubble.js
- packages/site/examples/point/scatter/demo/scatter.js
> feat: 柱图/条形图/饼图/散点图示例迁移

- .eslintrc.js
- packages/f2/src/base/component.ts
- packages/f2/src/components/axis/axisView.tsx
- packages/f2/src/components/axis/polar/polar-x.tsx
- packages/f2/src/components/axis/polar/polar-y.tsx
- packages/f2/src/components/axis/rect/bottom.tsx
- packages/f2/src/components/axis/rect/left.tsx
- packages/f2/src/components/axis/rect/right.tsx
- packages/f2/src/components/axis/rect/top.tsx
- packages/f2/src/components/axis/types.ts
- packages/f2/src/components/axis/withAxis.tsx
- packages/react/src/index.tsx
> feat: 完善 ts 定义

- .eslintignore
> feat: ignore test file

- packages/f2/src/base/component.ts
- packages/f2/src/components/axis/axisView.tsx
- packages/f2/src/components/axis/rect/bottom.tsx
- packages/f2/src/components/axis/rect/left.tsx
- packages/f2/src/components/axis/rect/right.tsx
- packages/f2/src/components/axis/rect/top.tsx
- packages/f2/src/components/axis/types.ts
- packages/f2/src/components/axis/withAxis.tsx
- packages/f2/src/util/index.ts
- packages/f2/test/components/axis.test.tsx
> feat: 完善 axis 类型定义

- packages/f2/src/attr/base.ts
- packages/f2/src/base/component.ts
- packages/f2/src/base/diff-recursive.ts
- packages/f2/src/base/diff.ts
- packages/f2/src/canvas/animation/animator.ts
- packages/f2/src/canvas/index.ts
- packages/f2/src/controller/interaction/base.ts
- packages/f2/src/jsx/render.ts
- packages/f2/src/mixins/theme.ts
> fix: lint warning

- packages/f2/src/components/geometry/index.tsx
- packages/f2/src/components/point/pointView.tsx
- packages/f2/src/controller/attr.ts
- packages/f2/test/components/line/line.test.tsx
> scale type 不生效问题

- packages/f2/src/components/line/lineView.tsx
- packages/f2/src/components/line/withLine.tsx
> fix: line points 不存在origin

- packages/f2/src/components/axis/types.ts
- packages/f2/src/components/axis/withAxis.tsx
- packages/f2/src/components/geometry/index.tsx
- packages/f2/src/components/geometry/interface.ts
- packages/f2/src/components/line/lineView.tsx
- packages/f2/src/components/line/types.ts
- packages/f2/src/components/line/withLine.tsx
- packages/f2/src/components/pieLabel/withPieLabel.tsx
- packages/f2/src/components/tooltip/withTooltip.tsx
> feat: 补充 line 类型定义

- packages/f2/src/components/geometry/index.tsx
- packages/f2/src/components/line/withLine.tsx
> fix: 修复 geometry.getSnapRecords

- packages/f2/test/timeline/interval-treemap.test.tsx
- packages/react/src/index.tsx
- packages/react/typings.d.ts
- packages/site/gatsby-config.js
- packages/site/package.json
refer: https://github.com/microsoft/monaco-editor/issues/2738
> fix: 修复官方示例报错 languageDefinitions is undefined

- .eslintrc.js
> fix: 去掉lint jsx no unused vars warn

- packages/f2/src/components/axis/polar/polar-x.tsx
- packages/f2/src/components/axis/polar/polar-y.tsx
- packages/f2/src/components/axis/rect/bottom.tsx
- packages/f2/src/components/axis/rect/left.tsx
- packages/f2/src/components/axis/rect/right.tsx
- packages/f2/src/components/axis/rect/top.tsx
- packages/f2/src/components/axis/types.ts
- packages/f2/src/components/axis/withAxis.tsx
- packages/f2/src/components/point/pointView.tsx
- packages/f2/test/components/axis/axis.test.tsx
- packages/f2/test/components/axis/data/bubble.json
> feat: axis的label和grid支持Function配置

- packages/f2/src/chart/index.ts
> fix: 修复update时, coord 位置不对

- packages/f2/src/canvas/index.ts
- packages/f2/src/components/geometry/interface.ts
- packages/f2/src/components/point/index.tsx
- packages/f2/src/components/point/withPoint.tsx
- packages/f2/src/jsx/interface.d.ts
- packages/f2/src/jsx/jsx-automatic.ts
- packages/f2/src/jsx/jsx-classic.ts
- packages/f2/src/jsx/renderJSXElement.ts
- packages/f2/test/components/area.test.tsx
- packages/f2/test/components/area/area.test.tsx
- packages/f2/test/components/line/line.test.tsx
- packages/f2/test/components/point/point.test.tsx
> fix: 完善JSX.Element type的类型

- packages/f2/tsconfig.json
- packages/f2/typing.d.ts
- packages/f2/typings/typing.d.ts
- packages/graphic/tsconfig.json
- packages/react/src/index.tsx
- packages/react/tsconfig.json
- packages/react/typings.d.ts
- packages/site/tsconfig.json
- typings.d.ts
> chore: 整理tsconfig文件，去掉一些重复的配置

- packages/graphic/src/engine/element.ts
- packages/graphic/src/engine/shape/arc.ts
- packages/graphic/src/engine/shape/circle.ts
- packages/graphic/src/engine/shape/custom.ts
- packages/graphic/src/engine/shape/image.ts
- packages/graphic/src/engine/shape/line.ts
- packages/graphic/src/engine/shape/marker.ts
- packages/graphic/src/engine/shape/polygon.ts
- packages/graphic/src/engine/shape/polyline.ts
- packages/graphic/src/engine/shape/rect.ts
- packages/graphic/src/engine/shape/sector.ts
- packages/graphic/src/engine/shape/shape.ts
- packages/graphic/src/engine/shape/text.ts
> feat: 修改类型定义

- packages/site/docs/tutorial/getting-started.en.md
- packages/site/docs/tutorial/getting-started.zh.md
> docs: 修改getting-started里几处错误的描述

- packages/f2/src/components/interval/label/index.ts
- packages/f2/src/components/interval/label/polygonLabel.tsx
- packages/f2/src/components/interval/view/polygonView.tsx
- packages/f2/src/components/interval/withInterval.tsx
- packages/f2/src/util/coord.ts
- packages/f2/test/components/interval/example/funnel.test.tsx
- packages/f2/test/components/interval/example/pyramid.test.tsx
- packages/site/examples/funnel/funnel/demo/basic.js
- packages/site/examples/funnel/funnel/demo/stroke.js
- packages/site/examples/funnel/pyramid/demo/basic.js
- packages/site/examples/funnel/pyramid/demo/scale.js
- packages/site/examples/funnel/pyramid/demo/stroke.js
- 补充了 IntervalLabel（目前只支持漏斗图和金字塔图、柱状图需要扩展 labelView）
> feat: Interval Label

- packages/f2/src/components/axis/rect/bottom.tsx
- packages/f2/src/components/axis/rect/top.tsx
- packages/f2/src/components/axis/types.ts
- packages/f2/src/components/tooltip/tooltipView.tsx
- packages/f2/src/index.ts
- packages/f2/src/jsx/compareRenderTree.ts
- packages/f2/src/jsx/interface.d.ts
- packages/f2/src/jsx/jsx-automatic.ts
- packages/f2/src/jsx/jsx-classic.ts
- packages/f2/src/types.ts
- packages/f2/test/components/axis/axis.test.tsx
- packages/graphic/src/types.ts
> feat: 补全element props ts 类型

- packages/f2/src/components/legend/legendView.tsx
- packages/f2/src/components/legend/withLegend.tsx
- packages/f2/test/components/legend.test.tsx
- packages/site/examples/line/multiple/demo/series.js
- packages/site/gatsby-browser.js
- packages/site/package.json
- 修复 Legend position 为 'bottom' 不显示的问题
- 扩展了 Legend 事件触发
- 补充了 Legend 动态交互示例
> fix: 完善 Legend

- package.json
> chore: 修改publish 命令

- packages/site/package.json
> deps: 升级官网主题包

- gatsby-config.js
- package.json
- site/pages/index.zh.tsx
> chore: 升级官网主题，并修改官网部分描述

- packages/f2/src/components/axis/types.ts
- packages/f2/src/components/axis/withAxis.tsx
- packages/f2/src/components/geometry/index.tsx
- packages/f2/test/components/interaction/pan.test.tsx
> fix: 修复update逻辑下 mapping 的问题 && 手势交互的bug

- packages/f2/src/components/area/withArea.tsx
- packages/f2/src/components/geometry/index.tsx
- packages/f2/src/components/line/withLine.tsx
> fix:Geometry支持sortable

- packages/f2/src/components/axis/types.ts
- packages/f2/src/components/axis/withAxis.tsx
- packages/f2/test/components/axis/axis.test.tsx
> fix: tickStyle传入基础类型报错

- packages/site/gatsby-config.js
> fix: 官网默认版本号显示问题

- packages/f2/src/components/geometry/index.tsx
- packages/f2/src/components/guide/withGuide.tsx
- packages/f2/src/components/line/withLine.tsx
> fix: 修复 line rerender 报错 和 guide 不能点击的问题

- packages/f2/.fatherrc.js
- packages/f2/src/components/axis/rect/bottom.tsx
- packages/f2/src/components/pieLabel/withPieLabel.tsx
- packages/f2/src/index.ts
- packages/f2/src/timeline.ts
> feat: f2 新增 umd 构建包

- packages/f2/src/components/tooltip/tooltipView.tsx
- 修复 xScale 为 timeCat 类型时显示不正确
- 增加 tooltipMarkerStyle
> feat: tooltip 功能完善

- packages/f2/test/canvas/lifecycle.test.tsx
> test: 补全生命周期处理的单测断言

- packages/f2/package.json
- packages/f2/src/canvas/animation/index.ts
- packages/f2/src/canvas/index.ts
- packages/f2/src/index.ts
- packages/f2/src/timeline.ts
- packages/f2/test/components/legend.test.tsx
- packages/f2/test/components/line/line.test.tsx
- packages/f2/test/components/line/radar.test.tsx
- packages/f2/test/index.test.ts
- packages/f2/test/timeline/interval.test.tsx
- packages/f2/test/util.ts
> fix: 调整timeline，去掉canvas 对 timeline 的依赖

- packages/f2/src/canvas/index.ts
- packages/f2/test/canvas/graphic.test.tsx
- packages/f2/test/canvas/theme.test.tsx
- packages/f2/test/components/line/line.test.tsx
- packages/f2/test/timeline/interval.test.tsx
- packages/graphic/src/engine/container.ts
- packages/graphic/src/engine/shape/text.ts
> fix: 修复默认字体设置不生效

- package.json
- packages/f2/.fatherrc.js
- packages/f2/src/components/guide/withGuide.tsx
- packages/f2/test/components/guide.test.tsx
> fix: guide records 数据映射逻辑修改

- packages/f2/src/components/tooltip/withTooltip.tsx
- packages/f2/test/components/tooltip/tooltip.test.tsx
- packages/f2/test/util.ts
> feat: tooltip onChange event

- packages/f2/src/attr/category.ts
- packages/f2/src/controller/attr.ts
- packages/f2/test/components/geometry/attr.test.tsx
- packages/f2/test/components/line/line.test.tsx
> fix: 修复 attr 和 scale 不一样的情况

- packages/f2/src/components/interval/view/polar.tsx
- packages/f2/src/components/interval/view/polygonView.tsx
- packages/f2/src/components/interval/view/rect.tsx
- packages/f2/src/components/interval/withInterval.tsx
- packages/f2/src/components/tooltip/tooltipView.tsx
- packages/f2/test/components/tooltip/tooltip.test.tsx
> fix: interval style

- packages/f2/src/chart/index.ts
- packages/f2/src/components/interval/withInterval.tsx
- packages/f2/src/controller/scale.ts
- packages/f2/src/mixins/scale.ts
- packages/f2/test/components/interval/interval.test.tsx
- 增加了 scale range 的处理逻辑
- 补了 scale controller 内的类型定义
> fix: adjust scale range

- packages/site/examples/line/multiple/demo/shapes.js
> docs: 修复 demo 中的错误代码

- packages/f2/jsx-runtime.d.ts
> chore: 修改jsx runtime 类型引用路径

- packages/my/src/index.tsx
> feat(f2-my): 优化 AppX2 下 canvas 组件宽高设置

- packages/f2/src/chart/index.ts
- packages/f2/src/components/tooltip/withTooltip.tsx
- packages/f2/test/components/tooltip/tooltip.test.tsx
> feat(tooltip): 默认展示 tooltip

- packages/f2/src/components/geometry/interface.ts
- packages/f2/test/components/canvas/animation.test.tsx
- packages/f2/test/components/guide/type.test.tsx
- packages/f2/test/components/interval/example/bar.test.tsx
- packages/f2/test/components/interval/example/column.test.tsx
- packages/f2/test/components/interval/example/doughnut.test.tsx
- packages/f2/test/components/interval/example/funnel.test.tsx
- packages/f2/test/components/interval/example/pie.test.tsx
- packages/f2/test/components/interval/example/pyramid.test.tsx
- packages/f2/test/components/legend/position.test.tsx
- packages/f2/test/components/pieLabel/pieLabel.test.tsx
- packages/f2/test/components/tooltip/tooltip.test.tsx
- packages/f2/test/jsx/render.test.tsx
- packages/f2/test/timeline/china-gdp.test.tsx
- packages/f2/test/timeline/dynamic-bubble.test.tsx
- packages/f2/test/timeline/index.test.tsx
- packages/f2/test/timeline/interval-adjust.test.tsx
- packages/f2/test/timeline/interval-treemap.test.tsx
- packages/f2/test/timeline/line-race.test.tsx
- packages/f2/test/timeline/race-country.test.tsx
- packages/site/examples/basic/demo/basic.jsx
> chore: 去掉一些 ts-ignore 注释

- packages/f2/src/base/component.ts
- packages/f2/src/chart/index.ts
- packages/f2/src/components/axis/withAxis.tsx
- packages/f2/src/components/legend/withLegend.tsx
> fix: 修改 coord 的布局调整逻辑

- package.json
> chore: 去掉 publish 的 prerelease

- packages/site/examples/basic/demo/basic.jsx
> docs: 调整 demo 默认样式

- packages/f2/src/components/geometry/index.tsx
> feat: geometry 透出 getAttr 方法

- packages/f2/src/components/area/areaView.tsx
- packages/f2/src/components/point/pointView.tsx
> fix: area point 没透传 animation

- package.json
- src/global.js
> chore: release 3.8.10

- packages/f2/src/components/interval/view/polar.tsx
> fix: 饼图的动画配置不生效

- packages/site/examples/column/column/demo/selection.js
- packages/site/examples/pie/pie/demo/meta.json
- packages/site/examples/pie/pie/demo/selection.js
> site: 官网补充图表选中的案例

- packages/f2/src/components/index.ts
> fix: 导出 gauge hoc

- packages/site/docs/tutorial/getting-started.zh.md
- packages/site/docs/tutorial/jsx-transform.zh.md
- packages/site/docs/tutorial/miniprogram.zh.md
- packages/site/docs/tutorial/nodejs.zh.md
- packages/site/docs/tutorial/shape-attrs.zh.md
> docs: 补充一些使用文档

- packages/f2/src/components/axis/types.d.ts
- packages/my/examples/test/mini.project.json
- packages/my/examples/test/package.json
- packages/my/examples/test/pages/index/_index.js
- packages/my/examples/test/pages/index/chart.js
- packages/my/examples/test/pages/index/chart.jsx
- packages/my/examples/typescript/mini.project.json
- packages/my/examples/typescript/package.json
- packages/my/examples/typescript/src/pages/index/chart.tsx
- packages/my/src/index.axml
- packages/my/src/index.tsx
- packages/wx/examples/test/package.json
- packages/wx/examples/test/pages/index/chart.js
- packages/wx/examples/test/pages/index/chart.jsx
- packages/wx/examples/test/project.config.json
- packages/wx/src/index.ts
- packages/wx/src/index.wxml
> feat: 小程序支持 click 事件

- packages/f2/src/canvas/animation/animator.ts
- packages/f2/src/canvas/animation/index.ts
- packages/f2/src/canvas/animation/interface.ts
- packages/f2/src/components/interval/view/polar.tsx
- packages/f2/src/components/line/lineView.tsx
- packages/f2/src/coord/polar.ts
- packages/f2/src/jsx/animation/index.ts
- packages/f2/src/jsx/createClipElement.ts
- packages/f2/src/jsx/render.ts
- packages/graphic/src/engine/element.ts
> feat: 饼图入场动画

- packages/f2/src/jsx/jsx-namespace.d.ts
- packages/f2/src/types.ts
- packages/site/docs/tutorial/question/with-react-typescript.zh.md
- packages/site/gatsby-config.js
> docs: 增加ts类型报错的解决文档

- gatsby-config.js
- package.json
> site: 修改 3.x 站点域名

- packages/site/gatsby-config.js
> site: 切换 4.x 官网域名

- package.json
> chore: 去掉 npm next tag

- package.json
- packages/f2/package.json
- packages/site/gatsby-config.js
ref: https://github.com/antvis/gatsby-theme-antv/pull/376/files
> fix: 官网 demo riddle 打开时报错

- packages/site/examples/creative/case/demo/apple-watch.jsx
> feat: 添加 F2 jsx 版本的 apple-watch

- packages/site/docs/api/chart/legend.zh.md
- packages/site/docs/api/f2.en.md
- packages/site/docs/api/f2.zh.md
- packages/site/docs/tutorial/component.zh.md
- packages/site/docs/tutorial/graphic.zh.md
- packages/site/docs/tutorial/jsx-transform.zh.md
- packages/site/docs/tutorial/shape-attrs.zh.md
- packages/site/docs/tutorial/shape.zh.md
> docs: 补全图形标签文档

- packages/site/docs/tutorial/shape.zh.md
- packages/site/examples/docs/shape/demo/shape.jsx
> docs: 文档里添加 playground 代码演示

- CHANGELOG.md
> chore: 更新 changelog

- packages/f2/src/components/guide/views/Image.tsx
- packages/f2/src/components/guide/views/Line.tsx
- packages/f2/src/components/guide/views/Point.tsx
- packages/f2/src/components/guide/views/Tag.tsx
- packages/f2/src/components/guide/views/Text.tsx
- packages/f2/test/components/guide/guide.test.tsx
> feat: guide offset 支持 px 单位

- packages/f2/src/components/geometry/index.tsx
- packages/f2/src/components/tooltip/withTooltip.tsx
> fix: tooltip 支持滑出画布外面

- packages/site/examples/radar/radar/demo/meta.json
- packages/site/examples/radar/radar/demo/radar-fill.jsx
> docs: 添加雷达图网格背景设置的demo

- packages/f2/src/components/legend/withLegend.tsx
> fix: revert legend setItems

- src/geom/base.js
> fix: 修复 getSnapRecords 超出边界时，获取不到值

- package.json
- src/global.js
> Chore 3.8.11

- packages/f2/src/base/updater.ts
> fix: setState 后，callback 队列没有清空

- packages/site/examples/creative/case/demo/meta.json
- packages/site/examples/creative/case/demo/radar.jsx
> site: 添加雷达图的动画案例

- packages/f2/src/base/diff.ts
- packages/f2/src/canvas/index.ts
- packages/f2/src/jsx/render.ts
- packages/f2/src/util/index.ts
- packages/f2/test/components/canvas/px2hd.test.tsx
> fix: 自定义px2hd。 Closed #1462

- CONTRIBUTING.md
- CONTRIBUTING.zh-CN.md
- README.en-US.md
- README.md
> docs: 更新 CONTRIBUTING 文档

- packages/site/docs/tutorial/nodejs.zh.md
- packages/site/docs/tutorial/vue.zh.md
> docs: 添加 vue 的使用文档

- packages/vue/examples/vue3/src/App.vue
> fix: vue3 示例报错

- packages/vue/examples/vite/package.json
- packages/vue/examples/vue3/package.json
> chore: 修改 vue 示例的依赖

- packages/my/package.json
- packages/react/package.json
- packages/vue/package.json
- packages/wx/package.json
> chore: package 添加 keywords

- packages/f2/package.json
- packages/my/package.json
- packages/react/package.json
- packages/vue/package.json
- packages/wx/package.json
> chore: package 添加 description 描述

- packages/vue/src/index.ts
> fix: 修复 vue unmount 时销毁 canvas

- packages/f2/src/components/legend/withLegend.tsx
> fix: itemWidth 改成同步设置

- packages/f2/src/components/interval/view/rect.tsx
- packages/f2/src/components/interval/withInterval.tsx
> fix: interval 默认动画调整

- packages/f2/package.json
- packages/my/package.json
- packages/react/package.json
- packages/vue/package.json
- packages/wx/package.json
> chore: 修改 keywords

- packages/site/examples/creative/case/demo/race-country.jsx
> docs: 修改动态排序图demo

- packages/f2/src/components/tooltip/withTooltip.tsx
> fix: 修复 tooltip 数据更新时，defaultItem 为 空的报错. Closed #1487

- packages/f2/package.json
- packages/my/package.json
- packages/react/package.json
- packages/vue/package.json
- packages/wx/package.json
> chore: 补充 & 完善 package.json

- packages/site/docs/tutorial/vue.zh.md
> docs: vue 添加 codesandbox 在线示例

- packages/f2/test/components/tooltip/tooltip.test.tsx
- packages/react/src/index.tsx
- packages/react/test/chart.test.tsx
> feat: React 组件增加 onError 事件透出

- packages/react/test/chart.test.tsx
> fix: 去掉 react 单测里的 console.error 输出

- packages/f2/src/components/line/lineView.tsx
- packages/f2/test/timeline/interval-treemap.test.tsx
> fix: 修复 line 图形变化

- packages/f2/src/components/legend/withLegend.tsx
- packages/f2/test/components/legend/legend.test.tsx
- packages/site/docs/api/chart/legend.zh.md
> feat: Legend 支持 onClick 回调. Closed #1511

- packages/my/examples/test/mini.project.json
- packages/my/examples/typescript/mini.project.json
> fix: 支付宝小程序示例点击不生效

- packages/my/src/index.tsx
> fix: 微信小程序点击位置不正确。Closed #1517

- packages/f2/src/components/interval/view/rect.tsx
- packages/f2/src/components/point/pointView.tsx
> fix: 修复小程序缩放后点图位置显示不正确。Closed #1520

- packages/f2/src/components/area/areaView.tsx
- packages/f2/src/components/line/lineView.tsx
- packages/f2/src/components/line/withLine.tsx
> chore: 修改雷达图默认动画

- package.json
- packages/f2/package.json
- packages/f2/test/components/canvas/px2hd.test.tsx
- packages/graphic/package.json
- packages/my/package.json
- packages/react/package.json
- packages/react/test/chart.test.tsx
- packages/site/package.json
- packages/vue/package.json
- packages/wx/package.json
> chore: 发布 5.0 beta 版本

- packages/graphic/src/engine/container.ts
> fix: 修复 children 为空的报错

- packages/site/docs/tutorial/miniprogram.zh.md
> docs: Update miniprogram.zh.md

- packages/site/examples/pie/donut/demo/donut.jsx
- packages/site/examples/pie/donut/demo/progress-bar.jsx
> fix: 修复官网条形图&进度条报错

- .github/workflows/gitleaks.yml
- packages/f2/src/components/geometry/index.tsx
- packages/f2/test/components/line/empty-data.test.tsx
> fix(line): 数据为空时,图表更新渲染失败

- packages/f2/src/types.ts
> fix: fix SupportPx type

- package.json
> chore: 添加 beta 命令

- packages/graphic/src/engine/container.ts
> fix: add 时 children 有可能为空

- packages/site/examples/other/area/demo/custom-gauge.jsx
- packages/site/examples/other/area/demo/meta.json
> docs: 添加自定义仪表盘

- .github/workflows/ci.yml
- packages/f2/package.json
- packages/my/package.json
- packages/site/package.json
> deps: grahpic semver 改成波浪号

- package.json
> chore: 修改 beta 的发布参数

- packages/f2/src/base/component.ts
- packages/f2/src/base/diff.ts
- packages/f2/src/base/updater.ts
- packages/f2/test/base/component.test.tsx
> fix: destroy 组件不再触发 setState 更新

- packages/site/examples/column/column/demo/pattern.jsx
> docs: 修复 pattern 的示例错误

- packages/site/docs/api/chart/guide.zh.md
> docs: 补充 tag guide 的文档内容

- packages/site/examples/pie/donut/demo/double-donut.jsx
- packages/site/examples/pie/donut/demo/meta.json
> docs: 添加双环图的demo

- packages/site/docs/tutorial/shape.zh.md
> docs: 文档添加 image 标签的使用

- packages/f2/src/components/zoom/index.tsx
> fix: 事件名修改

- packages/f2/src/base/diff.ts
- packages/f2/src/canvas/index.ts
- packages/f2/src/components/zoom/index.tsx
- packages/f2/test/canvas/lifecycle.test.tsx
> fix: 修复组件销毁未卸载

- packages/f2/src/components/guide/views/Image.tsx
- packages/f2/test/components/guide/guide.test.tsx
增加一个 cacheImage 参数，否则在update的时候会触发图表闪动的问题
> fix: imageGuide 缓存

- packages/site/docs/api/chart/axis.zh.md
- packages/site/docs/api/chart/chart.zh.md
- packages/site/docs/api/chart/geometry.zh.md
- packages/site/docs/api/chart/guide.zh.md
- packages/site/docs/api/chart/legend.zh.md
- packages/site/docs/api/chart/scroll-bar.zh.md
- packages/site/docs/api/chart/tooltip.zh.md
- packages/site/docs/tutorial/advanced/custom-view.md
- packages/site/docs/tutorial/graphic.zh.md
- packages/site/examples/point/scatter/demo/meta.json
- packages/site/examples/point/scatter/demo/roam.jsx
> docs: 补充官网文档

- packages/f2/src/index.ts
- packages/f2/src/theme.ts
> fix: 添加主题设置

- packages/react/src/index.tsx
> fix: react update

- packages/f2/package.json
- packages/f2/src/deps/f2-scale/src/util/time.ts
- packages/site/package.json
> fix: 修复 fecha 的依赖问题

- packages/f2/src/chart/index.ts
- packages/f2/src/components/sunburst/withSunburst.tsx
- packages/f2/src/components/treemap/withTreemap.tsx
- packages/f2/src/index.ts
- packages/f2/src/theme.ts
> fix: 修复 react theme 取不到的问题

- packages/f2/src/components/guide/views/Image.tsx
> fix: 修复 ImageGuide 位置计算错误

- src/scale/linear-tick.js
- test/unit/scale/linear-tick-spec.js
> fix: mix 坐标轴min为负，且count = 2的情况

- package.json
- src/global.js
> Chore release 3.8.12

- packages/site/docs/tutorial/shape.zh.md
> fix: 修复图形标签文档中，直线绘制坐标属性名错误

- packages/f2/src/chart/index.ts
- packages/f2/src/components/zoom/index.tsx
- packages/f2/src/controller/scale.ts
- packages/f2/test/components/interaction/pan.test.tsx
> fix: 修复 pan pinch 事件交互的 case

- packages/f2/src/components/axis/rect/bottom.tsx
- packages/f2/src/components/axis/rect/left.tsx
- packages/f2/src/components/axis/rect/right.tsx
- packages/f2/src/components/axis/rect/top.tsx
> chore: 修改 symbol 的命名

- packages/f2/src/components/area/areaView.tsx
- packages/f2/src/components/interval/view/polar.tsx
- packages/f2/src/components/line/lineView.tsx
- packages/f2/test/components/interval/example/pie.test.tsx
> fix: clip bug & symbol 不定义

- packages/f2/src/components/guide/views/Lottie.tsx
> fix: lottie options

- src/interaction/base.js
> fix: 修复 interaction click 事件变现不一致

- package.json
- src/global.js
> chore: release 3.8.13

- packages/f2/test/timeline/interval-adjust.test.tsx
- packages/f2/test/timeline/interval-treemap.test.tsx
> chore: 调整部分单测

- packages/f2/src/chart/index.ts
- packages/f2/src/components/area/withArea.tsx
- packages/f2/src/components/axis/withAxis.tsx
- packages/f2/src/components/gauge/withGauge.tsx
- packages/f2/src/components/guide/withGuide.tsx
- packages/f2/src/components/interval/withInterval.tsx
- packages/f2/src/components/legend/withLegend.tsx
- packages/f2/src/components/line/withLine.tsx
- packages/f2/src/components/pieLabel/withPieLabel.tsx
- packages/f2/src/components/point/withPoint.tsx
- packages/f2/src/components/sunburst/withSunburst.tsx
- packages/f2/src/components/tooltip/withTooltip.tsx
- packages/f2/src/components/treemap/withTreemap.tsx
> feat: component 支持外部定义的 props 类型传入

- packages/f2/src/chart/index.ts
> fix: 修复一些 ts 报错

- packages/f2/src/components/interval/view/polar.tsx
> fix: interval animation

- packages/f2/test/components/guide/guide.test.tsx
> fix: 调整 guide 的失败阈值

- packages/f2/src/components/guide/views/Image.tsx
- packages/f2/src/components/guide/views/Lottie.tsx
- packages/f2/src/components/guide/withGuide.tsx
- packages/f2/src/components/interval/view/polar.tsx
> feat:  add style func && fix lottie xy

- packages/f2/jsx-dev-runtime.d.ts
- packages/f2/jsx-dev-runtime.js
- packages/f2/jsx-runtime.d.ts
- packages/f2/jsx-runtime.js
> fix: 修复 jsx runtime 入口的引用路径

- packages/f2/package.json
- packages/f2/src/components/treemap/treemapView.tsx
- packages/f2/src/components/treemap/withTreemap.tsx
- packages/f2/test/components/treemap/index.test.tsx
> fix: 修复 treemap 的类型定义和事件

- packages/f2/src/util/index.ts
- packages/f2/test/util/px2hd.test.ts
> fix: px2hd 浮点数计算错误

- packages/f2-react/package.json
> chore: f2-react 添加 sideEffects

- packages/react/package.json
- packages/vue/package.json
> fix: react & vue 的幽灵依赖

- packages/node/examples/babel.config.json
- packages/node/examples/package.json
- packages/node/examples/src/index.jsx
- packages/node/package.json
- packages/site/package.json
> chore: 添加 node.js 的例子

- packages/f2/src/components/axis/polar/polar-x.tsx
- packages/f2/src/components/axis/polar/polar-y.tsx
- packages/f2/src/coord/polar.ts
- packages/f2/src/util/vector.ts
> chore: 修改 gl-matrix 的使用方式

- packages/f2-node/examples/babel.config.json
- packages/f2-node/examples/package.json
- packages/f2-node/examples/src/index.jsx
- packages/f2-node/package.json
> chore: add node example

- .eslintrc.js
- packages/f2/src/components/scrollBar/withScrollBar.tsx
- packages/f2/src/components/zoom/index.tsx
- packages/f2/src/deps/f2-adjust/src/adjusts/adjust.ts
> fix: 修复 lint 的 warnings

- packages/f2/src/components/treemap/index.tsx
- packages/f2/src/components/treemap/treemapView.tsx
- packages/f2/src/components/treemap/withTreemap.tsx
> feat: treemap 支持 props 的扩展和定义

- packages/f2/src/components/geometry/index.tsx
- packages/f2/src/components/guide/withGuide.tsx
- packages/f2/src/components/interval/view/polar.tsx
- packages/f2/src/components/interval/view/rect.tsx
- packages/f2/src/components/pieLabel/pieLabeView.tsx
- packages/f2/src/components/pieLabel/withPieLabel.tsx
- packages/f2/src/components/sunburst/icicleView.tsx
- packages/f2/src/components/sunburst/sunburstView.tsx
- packages/f2/src/components/sunburst/withSunburst.tsx
> feat: 调整sunburst & guide & pie事件

- .github/workflows/develop.yml
> feat: add sync site action

- packages/f2/src/components/tooltip/tooltipView.tsx
> fix: tooltip arrow position

- packages/f2/src/attr/linear.ts
- packages/f2/test/attr/linear.test.ts
> chore: 优化 interpolate 的处理

- package.json
> feat: add scripts canary

- packages/f2/src/chart/index.tsx
- packages/f2/src/components/guide/withGuide.tsx
- packages/f2/src/components/sunburst/withSunburst.tsx
- packages/f2/test/components/canvas/canvas.test.tsx
- packages/f2/test/components/guide/guide.test.tsx
- packages/f2/test/components/interaction/mulInteraction.test.tsx
- packages/f2/test/components/interaction/roam.test.tsx
- packages/f2/test/timeline/interval.test.tsx
- packages/f2/test/util.ts
> fix: 修复 ci

- site/.dumirc.ts
> chore: 更新首页使用案例图片

- packages/f2/src/chart/index.tsx
> fix: 修复事件范围

- packages/f2/src/components/guide/views/Arc.tsx
- packages/f2/src/components/guide/views/Image.tsx
- packages/f2/src/components/guide/views/Line.tsx
- packages/f2/src/components/guide/views/Point.tsx
- packages/f2/src/components/guide/views/Rect.tsx
- packages/f2/src/components/guide/views/Tag.tsx
- packages/f2/src/components/guide/withGuide.tsx
> refactor: 调整 guide 的包围盒计算逻辑

- packages/node/examples/package.json
- packages/node/examples/src/svg.jsx
> chore: 添加 node.js 生成 svg 的例子

- packages/f2/src/components/geometry/index.tsx
> fix: radar tootip value=0

- packages/f2/src/components/geometry/index.tsx
> fix: tooltip 左边界  value = 0时会被过滤掉

- packages/f2/src/components/geometry/index.tsx
- packages/f2/test/components/line/line.test.tsx
> fix: 非线性映射 callback 回调支持 origin 入参

- packages/graphic/src/util/dom.ts
> fix: 兼容非dom环境的判空

- packages/f2/src/chart/index.tsx
> fix: 修复 chart 的 ts 类型报错

- site/.dumi/pages/benchmark/4/f2.js
- site/.dumi/pages/benchmark/4/index.tsx
- site/.dumi/pages/benchmark/5/index.tsx
- site/.dumi/pages/benchmark/data.json
- site/.dumi/pages/benchmark/index.tsx
- site/package.json
> feat: 添加 4.x 5.x benchmark

- site/.dumirc.ts
> fix: 添加 runtimePublicPath

- site/.dumi/pages/benchmark/4/index.tsx
- site/.dumi/pages/benchmark/5/index.tsx
> site: benchmark 添加 svg 和 webgl

- lerna.json
> chore(lerna): lerna 配置增加 exact

- .github/workflows/ci_schedule.yml
> chore(ci): 增加 ci 巡检

- .github/workflows/ci_schedule.yml
> chore(ci): 失败通知添加关键词描述

- packages/f2/test/controller/linear-tick.test.ts
> test(ticks): 补充 linear ticks 的单测

- packages/f2-react/package.json
- packages/f2-wordcloud/package.json
> chore(deps): 设置严格的依赖版本

- .github/workflows/auto-release.yml
- lerna.json
> chore(scripts): 修改 lerna version 为 fixed

- packages/f2/src/chart/index.tsx
- site/examples/candlestick/candlestick/demo/base.jsx
> fix(chart): 修复 gesture 重复创建

- site/.dumirc.ts
- site/package.json
> chore: site 的 benchmark 在 ios 9 报错

- packages/f2-my/examples/test/pages/index/chart.js
- packages/f2-my/examples/test/pages/index/chart.jsx
- packages/f2-my/examples/test/pages/index/index.js
- packages/f2-my/examples/test/pages/index/index.jsx
> chore: 修改小程序的默认示例

- packages/f2-algorithm/package.json
> fix: package name

- packages/f2/jsx-dev-runtime.js
- packages/f2/jsx-runtime.js
> chore(jsx): jsx runtime 导出模块改为 esm

- packages/graphic/package.json
> fix(grahpic): f2-graphic 有副作用，设置 sideEffects: true

- packages/f2/src/components/geometry/index.tsx
- packages/f2/test/components/geometry/index.test.tsx
> feat: fix geometry event

- .github/workflows/auto-release.yml
> chore(actions): 尝试修复 auto release 时生成的 changelog 不对

- .github/workflows/develop.yml
> chore(site): site build 指定 node 版本

- site/docs/tutorial/framework/svg-renderer.zh.md
> docs(site): 添加 svg 使用文档

- packages/f2/package.json
- packages/f2/test/chart/svg.test.tsx
> chore(test): 添加 svg 单测

- .github/workflows/site-deploy.yml
> chore(site): 修复 site 构建报错

- packages/my/src/index.tsx
> feat:增加小程序onError

- packages/f2/test/components/treemap/index.test.tsx
> chore(ci): treemap 测试用例没有销毁之前的实例，导致 ci 报错

- packages/f2/src/components/geometry/index.tsx
> fix(geometry): 修复 record 存在 NaN 时，sort 顺序不对

- package.json
> chore: npm 切到正式的 latest tag

- .github/workflows/auto-release.yml
- .github/workflows/build.yml
- .github/workflows/ci_schedule.yml
- .github/workflows/sync-to-gh-pages.yml
> chore(actions): 修改 action 的执行分支

- packages/f2/src/components/area/withArea.tsx
> refactor: 修改 areaView 的points 的顺序

- packages/react/src/index.tsx
> feat: autofit属性

- packages/react/src/index.tsx
> fix: parentNode未初始化

- packages/f2/test/timeline/interval.test.tsx
> chore: 竞速动画添加数字变化动画示例

- site/.dumirc.ts
Replace unstable `polyfill.io` w/ `polyfill.alicdn.com`.
See also: https://github.com/umijs/umi/pull/12150 and https://github.com/polyfillpolyfill/polyfill-service/issues/2835
> docs: replace `polyfill.io`

- packages/f2/src/components/guide/withGuide.tsx
> fix: player guide visible

- packages/f2/src/components/guide/views/Arc.tsx
- packages/f2/src/components/guide/views/Image.tsx
- packages/f2/src/components/guide/views/Line.tsx
- packages/f2/src/components/guide/views/Lottie.tsx
- packages/f2/src/components/guide/views/Point.tsx
- packages/f2/src/components/guide/views/Rect.tsx
- packages/f2/src/components/guide/views/Tag.tsx
- packages/f2/src/components/guide/views/Text.tsx
- packages/f2/src/components/guide/withGuide.tsx
> fix: guide超出范围不显示

- packages/f2-algorithm/package.json
> fix: algorithm package.json

- packages/f2/src/components/pictorial/pictorial.tsx
- packages/f2/test/components/pictorial/basic.test.tsx
> fix: symbolsize修改为width height

- site/package.json
- site/tsconfig.json
> chore: 升级官网主题

- packages/f2/package.json
>  chore: 升级fengine版本

- .github/workflows/ci.yml
- .github/workflows/ci_schedule.yml
> fix: 升级action-artifact

- .github/workflows/ci.yml
- .github/workflows/danger-js.yml
- package.json
- packages/f2/.fatherrc.js
- packages/f2/src/index.ts
> fix: 修改注入版本插件

- packages/f2/test/components/line/line.test.tsx
- site/.dumi/tsconfig.json
- site/examples/line/line/demo/meta.json
- site/examples/line/line/demo/step.jsx
> chore: 补充官网阶梯图demo

- packages/f2/src/components/tooltip/tooltipView.tsx
> fix: 修复 Tooltip itemMarkerStyle 样式优先级

- packages/f2/src/components/zoom/index.tsx
> feat: 增加onChange回调函数

- site/examples/column/column/demo/meta.json
- site/examples/column/column/demo/pictorial.jsx
> chore: 官网增加Pictorial组件例子

- site/.dumirc.ts
- site/examples/component/guide/demo/linestep.jsx
- site/examples/component/guide/demo/meta.json
> chore: 增加官网polylineGuide例子

- site/examples/creative/case/demo/player.jsx
> chore:修复官网例子

- packages/f2/src/components/tooltip/withTooltip.tsx
- packages/f2/test/components/tooltip/tooltip.test.tsx
> feat(tooltip):增加onShow与onHide钩子

- site/.dumirc.ts
- site/package.json
> feat: 官网增加link入口

- .github/workflows/auto-release.yml
- .github/workflows/build.yml
> chore: 测试发布通知机器人

- site/docs/tutorial/shape-attrs.zh.md
> chore: 修复文档

- site/docs/api/chart/guide.zh.md
> doc: 订正 TextGuide 示例

- .github/workflows/auto-release.yml
> chore: fix release yml

- .github/workflows/auto-release.yml
- .github/workflows/scripts/update.js
- .github/workflows/update-yuque.yml
> chore: 增加更新知识库workflow

- site/examples/column/column/index.zh.md
- site/examples/column/dodge/index.zh.md
- site/examples/column/stack/index.zh.md
- site/examples/funnel/funnel/index.zh.md
- site/examples/point/scatter/index.zh.md
> chore: 调整官网文档

- site/docs/api/chart/axis.zh.md
> chore: 调整文档

- .cursor/rules/translation.mdc
> chore: 增加translation

- packages/f2/src/components/pieLabel/withPieLabel.tsx
> fix: ts error

- site/docs/api/chart/guide/guide.zh.md
- site/docs/api/chart/guide/image-guide.zh.md
- site/docs/api/chart/guide/point-guide.zh.md
- site/docs/api/chart/guide/rect-guide.zh.md
- site/docs/api/chart/guide/tag-guide.zh.md
- site/docs/api/chart/guide/text-guide.zh.md
- site/examples/component/guide/demo/rect.jsx
- site/examples/component/guide/index.zh.md
> chore: 补充 rect guide 文档

- .github/workflows/auto-release.yml
- lerna.json
> chore: createRelease by github

- .github/workflows/sync-to-gh-pages.yml
> chore: 修复gh-page ci

- .github/workflows/ci_schedule.yml
> chore: fix CI_Schedule

- site/.dumi/global.ts
- site/.dumirc.ts
- site/package.json
> chore: 修复官网加载失败

- .github/workflows/issue-automated.yml
> chore: 解决npm报错
