antvis/F2

src/chart/chart.js, src/geom/base.js, src/util.js, test/demos/area.js, test/demos/interval.js, test/demos/pie.js
=> fix(chart): fixed bug of #15, getSnapRecords of pie

demos/legend-single-selectedMode.html, src/plugin/legend.js, test/unit/plugin/legend-spec.js
Closed #131 .
图例支持单选模式：
```js
chart.legend({
selectedMode: 'multiple' || 'single'  // 默认多选
})
```
=> feat: chart legend support single select mode.

src/plugin/tooltip.js, test/bug/issue-234-spec.js
=> fix: fix the problem that tooltipMarker not show. Closed #234.

src/graphic/util/style-parse.js
node-canvas渲染渐变色报错，TypeError: offset required
原因是gradient.addColorStop第一个参数必须是Number，而提供的是数字字符串
=> Fix:[node canvas gradient.addColorStop issue]

src/util/dom.js
ReactNative Version：0.55.4
f2 Version: 3.1.12
由于RN暂不支持babel7，所以只能使用3.1.x让RN暂时可以与Node环境一样可以渲染
=> 增强浏览器环境的判断，修复ReactNative被误判

src/graphic/util/bbox.js
`var attrs = {x: 10, y: 10, r: 10, startAngle: 0, endAngle: Math.PI, anticlockwise: false}`的半圆弧，aabb包围盒应为`{minX: 0, minY:10, maxX: 20,maxY:  20}`,原计算方法的结果是`{minX: 0, minY:0, maxX: 20,maxY:  20}`
=> fix(bbox.js): getBBoxFromArc方法对于整圆的判断错误，导致半圆弧的最小包围盒计算错误

package.json, src/global.js
chore: 发布时候babelrc & webpackrc & lintrc都带上了 这会影响工程本身
业务工程引入f2之后，本来用的babel6，结果f2的babelrc里写个依赖@babel/pre-env，还加了对应babel-plugin、这和业务工程本身冲突.
package.json的main直接到lib/index.js所以既然是编译物就不要把rc加进来污染业务工程.
=> chore: 发布时候babelrc & webpackrc & lintrc都带上了 这会影响工程本身

src/graphic/shape/arc.js, src/graphic/shape/sector.js, test/unit/graphic/group-spec.js, test/unit/graphic/shape/arc-spec.js
graphic/shape 中 Arc 和 Sector 两个类有表示角度方向的布尔值属性，目前名称为 clockwise, 但从使用看，它被直接传给`CanvasRenderingContext2D.arc()`:
```
...
context.beginPath();
context.arc(x, y, r, startAngle, endAngle, clockwise);
```
实际含义是“**逆时针**”，即当为 true 时表示逆时针，为 false 时表示顺时针。此外 BBox 对象的`getBBoxFromArc()`方法将对应形参命名为 anticlockwise，最好保持一致。
因此建议将此处的 clockwise 按实际含义改名为 anticlockwise ,以防今后的维护者困扰。
此参数仅为内部使用，[文档](https://www.yuque.com/antv/f2/api-g-shape#4wxvsx)中**并未**暴露给使用者，因此此改动不会导致 API 的变化。
=> fix: arc 与 sector 中 clockwise 参数改为 anticlockwise 以正确反映含义

CHANGELOG.md, package.json, src/global.js
*  发布时候babelrc & webpackrc & lintrc都带上了 这会影响工程本身 ([4c6f3b47](https://github.com/antvis/f2/commit/4c6f3b47963638f1cd0e4ab385fd3b790967d874))
*  默认增加guide point插件 ([28d9e0c4](https://github.com/antvis/f2/commit/28d9e0c4778280fc04b037420b51f4231ce5855a))
*  图例只支持分类数据 ([bfe50422](https://github.com/antvis/f2/commit/bfe5042207c916e17a1143329fd8cd123a077053))
*  修复图例过滤不考虑空数据的问题。 ([78ee9fca](https://github.com/antvis/f2/commit/78ee9fcaf6c2b657a05cbeaa6f696ff9a407f8c1))
*  Guide 的 position 百分比解析需要考虑原始数据中本身包含 '%' 的情况.Closed [#590](https://github.com/antvis/f2/pull/590). ([b299390c](https://github.com/antvis/f2/commit/b299390c45bb1c61ea2bb453b3cd5de8dff18db3))
=> chore: release 3.4.2

README.md, README.zh-CN.md, gatsby-config.js, package.json
=> 🚀 f2.antv.vision

src/graphic/shape/text.js, src/graphic/util/rect.js, src/util/common.js, test/unit/graphic/shape/text-spec.js
=> fix: 修复Shape.Text 在设置 rotate 之后 Box 宽高不正确的问题

src/geom/base.js, test/unit/geom/geom-spec.js
在 Gemo Base 中提供配置项 [Boolean] ignoreEmptyGroup, 初始值为 false, 向上兼容，在经过 _groupData 之后得到的分组数据，根据配置项，决定是否将不存在任何一个有 y 轴字段的数据分组剔除掉。
Fixes #716
=> fix: 修复数据经过分组之后，没有任何数据的分组也参与绘图计算，尤其是在柱状图中，会占用宽度.

src/chart/chart.js, src/chart/controller/scale.js, src/geom/base.js, test/bug/issue-140-spec.js, test/bug/issue-804-spec.js
=> fix: after changeData, scale incorrect. Closed #804

src/chart/chart.js, src/geom/base.js, test/unit/geom/geom-init-spec.js, test/unit/geom/geom-spec.js
```
const data = [
{
type: 'type1',
value: 1,
},
{
type: 'type2',
value: 5,
},
{
type: 'type3',
value: 10,
},
{
type: 'type4',
value: 20,
},
]
const chart = new F2.Chart({
id: 'el',
});
chart.source(data);
chart.line().position('type*value');
chart.render();
// Uncaught TypeError: Cannot read property 'scales' of undefined
chart.line().position('type*value');
```
=> fix: geom repaint

src/component/tooltip.js, test/unit/graphic/group-spec.js, test/unit/graphic/shape/text-spec.js, test/unit/plugin/tooltip-spec.js
可以使用配置 tooltip 的 xtip/ytip 文字样式了
```
chart.tooltip({
showXTip: true,
showYTip: true,
xTipTextStyle: {
fontSize: 12,
fill: '#fff',
},
yTipTextStyle: {
fontSize: 12,
fill: '#fff',
},
})
```
=> feat: 为 tooltip 的 xtip/ytip 增加 text 样式配置

packages/f2/src/attr/base.ts, packages/f2/src/attr/category.ts, packages/f2/src/attr/identity.ts, packages/f2/src/attr/linear.ts, packages/f2/src/controller/attr.ts, packages/f2/test/components/point/point.test.tsx
* 创建 attr 的时候不应该去判断数据的特征来创建不同类型的attr。
* 兜底用 Category Attr，因为 x、y 已经强制设置为 Linear 了
=> fix: attr 实例化时不判断数据相关的特征

packages/f2/src/canvas/index.ts, packages/react/test/chart.test.tsx
=> fix: 修复canvas.destroy报错

packages/f2/src/attr/base.ts, packages/f2/src/attr/linear.ts, packages/f2/src/components/axis/withAxis.tsx, packages/f2/src/components/geometry/index.tsx, packages/f2/src/components/interval/util.ts, packages/f2/src/components/interval/withInterval.tsx, packages/f2/src/components/line/lineView.tsx, packages/f2/src/components/line/withLine.tsx, packages/f2/src/components/point/pointView.tsx, packages/f2/src/components/sunburst/withSunburst.tsx, packages/f2/src/components/treemap/withTreemap.tsx, packages/f2/src/controller/attr.ts, packages/f2/src/controller/scale.ts, packages/f2/src/coord/base.ts, packages/f2/src/theme.ts, packages/f2/test/components/axis/axis.test.tsx, packages/f2/test/components/geometry/attr.test.tsx
=> fix: attr映射逻辑优化

packages/f2/src/components/geometry/index.tsx, packages/f2/src/components/sunburst/withSunburst.tsx, packages/f2/src/components/treemap/withTreemap.tsx, packages/f2/src/controller/scale.ts, packages/f2/src/coord/base.ts, packages/f2/test/components/interval/example/pie.test.tsx
* 修复了饼图的scale.nice = true导致mapping不符合预期的问题
* 修复了 sunburst 和 treemap的坐标映射问题
=> fix: 饼图scale适配调整

packages/f2/src/components/area/withArea.tsx, packages/f2/src/components/geometry/index.tsx, packages/f2/test/components/area/area.test.tsx, packages/f2/test/components/line/radar.test.tsx, packages/site/examples/area/area/demo/with-negative.js, packages/site/examples/radar/radar/demo/area.js, packages/site/examples/radar/radar/demo/basic.js
修复：https://github.com/antvis/F2/projects/1#card-72944540
原因：
- 面积图设置 `startOnZero` 为 `true`修改了 scale，scale 更新的时机不正确
=> fix: 雷达面积图坐标不一致问题

packages/f2/src/chart/index.ts, packages/f2/src/components/axis/withAxis.tsx, packages/f2/test/components/axis/axis.test.tsx, packages/f2/test/components/interaction/pan.test.tsx, packages/f2/test/util.ts
=> fix: 修复 axis rerender 不更新布局和 labelOffset 报错

packages/f2/src/components/legend/withLegend.tsx, packages/f2/test/components/legend/legend.test.tsx
两个问题：
- willMount 期间手动触发 render 时拿到的 this.state.items 为空数组，导致计算出来的 width 为 0
- isVertical = true 时没有 remove 掉用于计算时渲染的 shape
=> fix: 修复 legend maxItemWidth 计算错误

packages/f2/src/base/component.ts
=> fix: Component Render 返回类型

packages/f2/src/components/axis/rect/bottom.tsx, packages/f2/src/index.ts, packages/f2/src/types.ts
=> feat: 导出renderShape

src/graphic/engine/shape/polyline.js, test/unit/graphic/shape/polyline-spec.js
=> fix: 修复 polyline 只有1个点时，getbbox 计算不对

packages/f2/src/attr/base.ts, packages/f2/src/components/gauge/gaugeView.tsx, packages/f2/src/components/gauge/withGauge.tsx, packages/f2/src/components/index.ts, packages/f2/tsconfig.json, packages/f2/typing.d.ts, tsconfig.json
=> feat: 新增 Gauge 的 ts 类型定义

site/.dumirc.ts, site/examples/column/column/demo/pattern.jsx, site/examples/component/guide/demo/custom.jsx, site/examples/component/legend/demo/custom.jsx, site/examples/component/shape/demo/shape.jsx, site/examples/creative/case/demo/apple-watch.jsx, site/examples/creative/case/demo/line-race.jsx, site/examples/creative/case/demo/race-country.jsx, site/examples/other/area/demo/custom-gauge.jsx, site/examples/pie/donut/demo/donut.jsx, site/examples/pie/donut/demo/double-donut.jsx, site/examples/pie/pie/demo/labelline-pie.jsx, site/package.json
=> fix: 5.0 官网例子大部分跑通

packages/vue/examples/vue3/src/App.vue, packages/vue/src/index.ts
=> fix: vue 数据不更新

packages/f2/src/components/gauge/gaugeView.tsx, packages/f2/src/components/gauge/index.tsx, packages/f2/src/components/gauge/withGauge.tsx, packages/f2/src/components/index.ts
=> feat: gauge 支持 view 的 props ts 类型扩展

packages/f2/src/components/pieLabel/pieLabeView.tsx, packages/f2/test/components/pieLabel/pieLabel.test.tsx
=> fix:  pielabel 事件回调对象

.github/workflows/ci_schedule.yml
=> chore(ci): ci 巡检失败，上传 diff 图片

site/.dumirc.ts, site/package.json
=> chore: update dumi-theme-antv

packages/f2/src/components/tooltip/tooltipView.tsx, packages/f2/src/components/tooltip/withTooltip.tsx, packages/f2/test/components/tooltip/tooltip.test.tsx
=> fix: tooltip tips 透出 record 参数

package.json, packages/f2/.fatherrc.js, packages/f2/src/index.ts
=> feat: 构建注入version

site/package.json
=> chore: 修复官网报错

packages/f2/src/components/line/lineView.tsx
=> fix: EndView动画使用offsetDistance对不齐

packages/f2/src/components/treemap/withTreemap.tsx, packages/f2/test/components/treemap/index.test.tsx
=> chore: add selected in treemap
